name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ '138.68.103.40' }}
        username: ${{ 'ricihi' }}
        key: ${{ 'dossh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBo2Gksp06504arl9a3n8uibh9aMlXxdAUZtxzsSHz9B ricihi@ubuntu-rickserver-practicas' }}
        script: |
          cd /home/ricihi/repositories/tfm-ai-api-rickserver
          git pull
          docker compose down
          docker compose up -d --build