name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ '138.68.103.40' }}
        username: ${{ 'ricihi' }}
        key: ${{ 'bZ3IooP+1kBE5v1BlezaPfYR3xrbW9kJ2TxNWevRSt8c6iaDzU1BHRiG3GQtyRDnib7kAQE8wFtV08JPGvrm3VkfRX9rAWrwVcdtQIUU1MWbAVvlVND1DMjLmATTlXZfbWt3OP1DsvOT1QPxlupBF1zzw8Xmu/IY+hz2C+lPvDtYxy2FKWQ+Hry+H3qfHfKy10yzES5VL+ZFkYmZYYbKBVHXtIqSc7XkTXQJ40/amjXpcnm3Ml5MzCyalfjicdDsmXm4CvOu2/4thNg9K3V1AX/Qu9vrSJWrcETBzdEAAAEBAP481kWco6BgUlIB/Xl+CDuGwCZiAxXO5FdST85c5sEBTyncjnmmrNNP/5UhTIZylsQ644E8i0iQlF6MUdQT1dZOwysbynH8xfrmCM6hqxsAeJOKMfTxnJOw6vlyhyY1pEW37afQbbrr4iRkfyVyDpgWsH5sFHXDP3Sg5wjV0YJHY6LeMbu2aP9G9pozbPVsKf5HyuHZYH9CucioqGSE+ASU23VruXnWX1CmGNeKcPFSyof6BrDIxptHh8JAnE7fQWbO5pemIUNy/jQzF+gZkmBCJy8PCAw3OrXnUdmue/Box1CQgZOxjnrQlWAPnWhZ7NaNNGefI+mKgral4bw0MA0AAAEBANftsHEGDl/47U8F9w+cTJiWMRSMfY3xXBbBSsJXZ62eczlnVLxa+C8UXL0sJSNeyeRkx5coi659MrSmU7rlLOUQDRq1U9ZTPaVA0q+tCgD7DMvrNH3vTvN2EoNQFE8BSyPvNTMz6/MI8DW80QNuaI7lc26XLvOhg+OUZabg55ngUTYlhTHaemsrXRimLIek+sKXcTP0LyFGcoNthuCSkNpr0zqeIqFwO4eQcTD9E915Xbj7HHFZPR1bs6Wx0bhGnQ/n2zekm0VFlDjCVTj5E8nUqf91scKzE8zCsEaKwdg7BWxAIThianpaVDcOymIvf8/iUOsZp8bgID7ByDw8kIkAAAAWcmlja3NlcnZlcjI0QGdtYWlsLmNvbQECAwQF' }}
        script: |
          cd /home/ricihi/repositories/tfm-ai-api-rickserver
          git pull
          docker compose down
          docker-compose up -d --no-deps --build backend